steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia.gcr.io/trunk-work-school/sample-web:latest', '-f', '.docker/Dockerfile', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia.gcr.io/trunk-work-school/sample-web:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'asia.gcr.io/trunk-work-school/sample-web:latest', 'asia.gcr.io/trunk-work-school/sample-web:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia.gcr.io/trunk-work-school/sample-web:$SHORT_SHA']
timeout: 180s
tags: ['first', 'build']
images: ['asia.gcr.io/trunk-work-school/sample-web:latest','asia.gcr.io/trunk-work-school/sample-web:SHORT_SHA']

